// <auto-generated />
using GreenThumb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb.Migrations
{
    [DbContext(typeof(PlantDbContext))]
    [Migration("20231207202555_DeleteAndRecreateDatabase")]
    partial class DeleteAndRecreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instruction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"));

                    b.Property<string>("InstructionInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instruction_info");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            InstructionInfo = "Water the plant",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            InstructionInfo = "Your plant should flower after about 8 weeks.",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 3,
                            InstructionInfo = "Watering infrequently. They're a desert plant. Dry soil suits them fine",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 4,
                            InstructionInfo = "Keep your plant in a bright, sunny spot",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 5,
                            InstructionInfo = "Keep your plant in a bright, sunny spot",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 6,
                            InstructionInfo = "Provide 1 to 2 inches (2.5 to 5cm) of water each week",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 7,
                            InstructionInfo = "During fall and winter, you can water them less often.",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 8,
                            InstructionInfo = "During fall and winter, you can water them less often.",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 9,
                            InstructionInfo = "Mow New Grass and Control Weeds",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 10,
                            InstructionInfo = "Water thoroughly once or twice a week depending on weather conditions.",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 11,
                            InstructionInfo = "For a healthy grove of timber bamboo, remove old, dead, weak and leaning canes,",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 12,
                            InstructionInfo = "Keep your plant in a bright, sunny spot",
                            PlantId = 7
                        },
                        new
                        {
                            InstructionId = 13,
                            InstructionInfo = "4 feet tall: Apply 2 pounds of fertilizer ",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 14,
                            InstructionInfo = "10 feet tall: Apply 5 pounds of fertilizer ",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 15,
                            InstructionInfo = "20 feet tall: Apply 10 pounds of fertilizer",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 16,
                            InstructionInfo = "During fall and winter, you can water them less often.",
                            PlantId = 9
                        },
                        new
                        {
                            InstructionId = 17,
                            InstructionInfo = "The ideal indoor location for this plant is near a window with filtered sunlight.",
                            PlantId = 10
                        },
                        new
                        {
                            InstructionId = 18,
                            InstructionInfo = "Keep the soil evenly moist but not soggy during the growing season.",
                            PlantId = 10
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Description = "Bright yellow flowering plants known for their striking appearance and large, disk-like flower heads.",
                            Name = "Sunflower"
                        },
                        new
                        {
                            PlantId = 2,
                            Description = "Plants that have succulent stems, pads or branches with scales and spines instead of leaves.",
                            Name = "Cactus"
                        },
                        new
                        {
                            PlantId = 3,
                            Description = "Rose flowers vary in size and shape. They burst with colours ranging from pastel pink, peach, and cream, to vibrant yellow, orange, and red. Many roses are fragrant",
                            Name = "Rose"
                        },
                        new
                        {
                            PlantId = 4,
                            Description = "A tree is a tall plant that can live a very long time. It has a single stem or trunk and branches that support leaves.",
                            Name = "Tree"
                        },
                        new
                        {
                            PlantId = 5,
                            Description = "A low, green plant that grows naturally over a lot of the earth's surface.",
                            Name = "Grass"
                        },
                        new
                        {
                            PlantId = 6,
                            Description = "Bamboo is a type of fast-growing grass that is known for its strength and versatility.",
                            Name = "Bamboo"
                        },
                        new
                        {
                            PlantId = 7,
                            Description = "Ivy is a type of climbing plant that can grow on walls, trees, and other surfaces.",
                            Name = "Ivy"
                        },
                        new
                        {
                            PlantId = 8,
                            Description = "A palm tree is a type of tropical tree with a tall, slender trunk.",
                            Name = "Palm Tree"
                        },
                        new
                        {
                            PlantId = 9,
                            Description = "Bushes are often used for landscaping and can provide a natural barrier or privacy screen.",
                            Name = "Bush"
                        },
                        new
                        {
                            PlantId = 10,
                            Description = "Corn is a type of cereal grain that is grown for its edible seeds.",
                            Name = "Corn"
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.HasOne("GreenThumb.Models.PlantModel", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
